carries(txszqu, mvjqmad).
carries(txszqu, lwqlyjq).
carries(txszqu, jlgnsu).
carries(umnqkb, nbrvl).
carries(umnqkb, bcmbao).
carries(umnqkb, vfimqtl).
carries(xghhu, molth).
carries(xghhu, atqewc).
carries(fujwb, tyjyc).
carries(fujwb, xyemll).
carries(zqnjd, jxsmuey).
carries(zqnjd, uelnii).
carries(zqnjd, vcwezm).
carries(zqnjd, uxnwtp).
carries(lonwb, rydrp).
carries(lonwb, mgyixhn).
carries(lonwb, cjhtxo).
carries(mkrjamh, ecbog).
carries(mkrjamh, owaebx).
carries(vkhazkn, oactn).
carries(vkhazkn, ftxif).
carries(vkhazkn, rxlbou).
carries(vkhazkn, bkfav).
carries(rddnfg, mvgmbru).
carries(rddnfg, zlazoqs).
carries(pxlzcx, vjvit).
carries(pxlzcx, cnblx).
carries(pxlzcx, bwiqe).
carries(pxlzcx, pjsbxvk).
carries(pxlzcx, ipqjxa).
carries(pxlzcx, zkikz).
carries(offkzc, wymlvix).
carries(offkzc, felrwte).
carries(offkzc, bzublv).
carries(bavyg, szszezd).
carries(bavyg, lurhq).
carries(bavyg, ltncvl).
carries(bavyg, fmwvok).
carries(bavyg, frikrv).
carries(bavyg, tumwln).
carries(bavyg, xjtujzp).
carries(sjhwgq, ydqgvnf).
carries(sjhwgq, oztasey).
carries(sjhwgq, qkmkwgl).
carries(objssr, xujmi).
carries(objssr, oqihtt).
carries(vwksn, zwxxii).
carries(vwksn, owttcz).
carries(czmzol, qzayss).
carries(czmzol, ufrrrzi).
carries(eppufdw, brwsjee).
carries(eppufdw, laoouso).
carries(eppufdw, jgfcyze).
carries(mmtzk, utispep).
carries(mmtzk, onkhx).
carries(zoofu, cyczt).
carries(zoofu, qargs).
carries(ymkax, znmumx).
carries(ymkax, hnjuqgw).
carries(bpelccj, ctzhawr).
carries(bpelccj, qhldpg).
carries(dbexmj, bijprk).
carries(dbexmj, iotkxfd).
carries(fhdqcbx, gefut).
carries(fhdqcbx, mulybo).
carries(fbgguv, bkomu).
carries(fbgguv, tynxlau).
carries(fbgguv, sfruur).
carries(fbgguv, zxvbb).
carries(fbgguv, khupkt).
carries(fbgguv, xkntkvz).
carries(aahhxau, rbauxvx).
carries(aahhxau, neliq).
carries(xpzpv, mxtxm).
carries(xpzpv, kgzyk).
carries(xpzpv, yzpaxlz).
carries(xpzpv, vfxqcbq).
carries(xpzpv, lcgtwj).
carries(stwubkv, uzzeydh).
carries(stwubkv, zknpmnc).
carries(nkbmoin, vgqmfj).
carries(nkbmoin, weygson).
carries(nkbmoin, knbems).
carries(nkbmoin, gdmlk).
carries(nkbmoin, ecfrqpl).
carries(nkbmoin, tbaai).
carries(nkbmoin, sfohocq).
carries(twazofk, dntwqr).
carries(twazofk, vugavk).
carries(apqby, xkzlyvh).
carries(apqby, vlsjsgg).
carries(lptmne, fkjlcz).
carries(lptmne, jinwsas).
carries(lptmne, qnevjto).
carries(lptmne, wfjks).
carries(rtyegs, nhbbd).
carries(rtyegs, yqqun).
carries(cavlg, lsaroxx).
carries(cavlg, evkau).
carries(cavlg, gldgrng).
carries(kqswas, ntcddy).
carries(kqswas, bwqmns).
carries(kqswas, vtvsd).
carries(kqswas, oxoqy).
carries(xsfwcgq, inknun).
carries(xsfwcgq, seihhya).
carries(xsfwcgq, qrlhp).
carries(xsfwcgq, bchtcht).
carries(xsfwcgq, rswqvx).
carries(qnscqms, mernsee).
carries(qnscqms, ubjuhxp).
carries(qnscqms, mlfxnna).
carries(vfxzkq, ukrqfm).
carries(vfxzkq, pnsvthy).
carries(vfxzkq, qdcos).
carries(kkeuh, urfhlf).
carries(kkeuh, hjtkb).
carries(ckcjr, owgsk).
carries(ckcjr, vdnphf).
carries(jgfcyze, ziqyhi).
carries(jgfcyze, wrwgm).
carries(jgfcyze, hdikur).
carries(jgfcyze, bmqhrtg).
carries(pohdy, frcqooy).
carries(pohdy, idhvksi).
carries(xjtujzp, soryrk).
carries(xjtujzp, zkvopb).
carries(xjtujzp, xufneyr).
carries(ifgfg, jcbgta).
carries(ifgfg, aemyrqj).
carries(kwavcf, vmpmig).
carries(kwavcf, djeee).
carries(mdnqs, tpmhs).
carries(mdnqs, essvr).
carries(gqlyhql, uwrhuw).
carries(gqlyhql, ypanow).
carries(guauivo, puvhc).
carries(guauivo, bjcsjrr).
carries(guauivo, ccjtpv).
carries(guauivo, ibwve).
carries(guauivo, evbvdgl).
carries(guauivo, stwubkv).
carries(guauivo, kwxpnrs).
carries(pbohgz, sbfiv).
carries(pbohgz, igbhyk).
carries(pbohgz, rhxcyd).
carries(bkomu, krbpgmk).
carries(bkomu, ekgbf).
carries(bkomu, yqlxeb).
carries(bkomu, ogyiesm).
carries(bkomu, poypmax).
carries(yjoyyvl, sjioze).
carries(yjoyyvl, nigkvxl).
carries(yjoyyvl, itjxq).
carries(efobdsd, yqnso).
carries(efobdsd, glqspl).
carries(zxvbb, fvkxwt).
carries(zxvbb, xlanm).
carries(zxvbb, gxitq).
carries(cvrga, vagjk).
carries(cvrga, ghvpg).
carries(jnzqvia, divak).
carries(jnzqvia, cmgvs).
carries(qqnywdg, lrjnzf).
carries(qqnywdg, luhxcq).
carries(qqnywdg, whgpim).
carries(sfizdf, aahhxau).
carries(sfizdf, shiiodm).
carries(sfizdf, cvnfak).
carries(sfizdf, whjcp).
carries(tcvgl, ljfvbjd).
carries(tcvgl, bafnaij).
carries(uravet, hzzxjxa).
carries(uravet, mvdzfo).
carries(kjdjdr, kpdmptf).
carries(kjdjdr, hsqhwef).
carries(vycgaoz, jqulm).
carries(vycgaoz, ziwlgdb).
carries(gtpyffj, kcpwmyz).
carries(gtpyffj, emkzxk).
carries(gtpyffj, hwuabde).
carries(gtpyffj, efgqua).
carries(oxoqy, lktbqq).
carries(oxoqy, zukio).
carries(oxoqy, bcpbvya).
carries(xwwzp, lonfrp).
carries(xwwzp, eppufdw).
carries(xwwzp, nmxqs).
carries(ekgbf, bckbud).
carries(ekgbf, fzzlnwi).
carries(ekgbf, cvprip).
carries(ltncvl, sktewq).
carries(ltncvl, hydeeqe).
carries(ltncvl, ibdjxl).
carries(jcdmhvd, twgrfm).
carries(jcdmhvd, dxhrpq).
carries(znpvlac, vmyrdkl).
carries(znpvlac, aideelj).
carries(vifbi, rkwkwd).
carries(vifbi, onqax).
carries(vifbi, cfrcco).
carries(vifbi, onamlmy).
carries(vifbi, zoofu).
carries(vifbi, vwosnfn).
carries(hagrq, fhecgzf).
carries(hagrq, mefajk).
carries(hagrq, uyrxc).
carries(hagrq, gdclwzu).
carries(cvlkltp, guiej).
carries(cvlkltp, vffqp).
carries(fimqsn, ehvxt).
carries(fimqsn, xyoiv).
carries(fimqsn, mikast).
carries(xoqvvx, xawfk).
carries(xoqvvx, ojrjqv).
carries(xwwfi, cpjkea).
carries(xwwfi, hsexbak).
carries(xwwfi, dxaemlq).
carries(xwwfi, wlyzbz).
carries(shiiodm, hclea).
carries(shiiodm, nrduy).
carries(yrozpm, btukw).
carries(yrozpm, fbyju).
carries(onqax, vtlvs).
carries(onqax, ccnpjdf).
carries(tgwgno, yyyub).
carries(tgwgno, ofcyw).
carries(ztjquwi, ptawnqq).
carries(ztjquwi, ziprwty).
carries(ztjquwi, yzfzbw).
carries(ztjquwi, hpqux).
carries(ztjquwi, baaqr).
carries(ztjquwi, bwugxhi).
carries(bchtcht, rsvixyg).
carries(bchtcht, cppdkv).
carries(htujh, nzhnurq).
carries(htujh, btbnj).
carries(htujh, ghsxqq).
carries(ofyuao, llhiw).
carries(ofyuao, nbjpcc).
carries(dvipr, udnmqte).
carries(dvipr, osnjzpt).
carries(dvipr, swujbg).
carries(ybnehoi, hatmr).
carries(ybnehoi, alkizae).
carries(xkntkvz, lwugjj).
carries(xkntkvz, cstmu).
carries(xkntkvz, rsjffj).
carries(xkntkvz, pxlzcx).
carries(xkntkvz, jtmuv).
carries(fhvyhk, boqgjn).
carries(fhvyhk, rzzezfx).
carries(jytapdu, vqvwkm).
carries(jytapdu, jpcseag).
carries(jytapdu, kgkpfg).
carries(bgpjb, aqaems).
carries(bgpjb, jkymeqw).
carries(gxitq, wshlljj).
carries(gxitq, krpda).
carries(gxitq, aasxby).
carries(gxitq, ywhjz).
carries(gxitq, stnnf).
carries(gxitq, nfkmi).
carries(ulehitr, knrtys).
carries(ulehitr, mnfep).
carries(wvhvw, xcckt).
carries(wvhvw, duzgl).
carries(gpqhjv, wzxqipp).
carries(gpqhjv, ykxnd).
carries(gpqhjv, dhsopiv).
carries(ipqjxa, gsmcgor).
carries(ipqjxa, inlcow).
carries(ipqjxa, hdmcpq).
carries(ipqjxa, xhmornc).
carries(ipqjxa, lisfhnn).
carries(pkceuqw, isqxwp).
carries(pkceuqw, evkrnfo).
carries(pkceuqw, pcqpqjk).
carries(vxwobup, sejkvk).
carries(vxwobup, olrdlw).
carries(vxwobup, hfxsib).
carries(hpqux, ocdzc).
carries(hpqux, xlvjz).
carries(gyuyu, xfurlrr).
carries(gyuyu, etlce).
carries(bfulyh, tjuqz).
carries(bfulyh, tzqdwe).
carries(bfulyh, ayeqoz).
carries(aasxby, lvcdsgp).
carries(aasxby, dhejgd).
carries(aasxby, nzvpgv).
carries(cmbnwse, jphmpr).
carries(cmbnwse, tlkhxww).
carries(crbcsqt, oakbrw).
carries(crbcsqt, dswjpxm).
carries(tzszs, jieijuo).
carries(tzszs, ndeop).
carries(yzpaxlz, heqbpd).
carries(yzpaxlz, dphmg).
carries(knbems, looigzn).
carries(knbems, qdkrr).
carries(bwqmns, dcgphc).
carries(bwqmns, wwzli).
carries(vtwdqkd, vcvayah).
carries(vtwdqkd, wyhnmbs).
carries(qilhudr, qbcar).
carries(qilhudr, wuwjp).
carries(qilhudr, umxurvd).
carries(aahqtsf, hfhswyd).
carries(aahqtsf, znpvlac).
carries(aahqtsf, bruqu).
carries(gybikf, uwnml).
carries(gybikf, noqjuo).
carries(vjvit, jdhewio).
carries(vjvit, wwhlo).
carries(vjvit, crbcsqt).
carries(zkikz, ttqpi).
carries(zkikz, ifdkle).
carries(zkikz, qdyzunw).
carries(zkikz, wkcrce).
carries(zkikz, jcezw).
carries(zkikz, qeiijk).
carries(nmxqs, sftqzaf).
carries(nmxqs, gyuyu).
carries(nmxqs, tkvmtol).
carries(nmxqs, vwksn).
carries(nmxqs, doppnr).
carries(bpgdb, jxpixqi).
carries(bpgdb, kygcziz).
carries(tmigcw, gmsjkn).
carries(tmigcw, njmlk).
carries(hwuabde, mvamo).
carries(hwuabde, bverp).
carries(wdzhfmw, galojia).
carries(wdzhfmw, ibyrsdo).
carries(dkoike, wuckr).
carries(dkoike, mfbnys).
carries(dkoike, gmrqpdk).
carries(atyaqz, asmysiq).
carries(atyaqz, paoitb).
carries(atyaqz, okpdcz).
carries(lwugjj, hykxm).
carries(lwugjj, hechfb).
carries(lwugjj, edtkfvv).
carries(lwugjj, lonwb).
carries(bnmshvm, vfmlyg).
carries(bnmshvm, ychjmik).
carries(azzysl, anhjp).
carries(azzysl, ixnlvyo).
carries(azzysl, mmndzs).
carries(azzysl, alaug).
carries(olevfy, wuipwl).
carries(olevfy, etvpko).
carries(olevfy, bavaf).
carries(tvcxl, vlmzodk).
carries(tvcxl, vbojbp).
carries(tvcxl, oldrtya).
carries(gdmlk, bgavnd).
carries(gdmlk, iqpcu).
carries(utojr, nuytv).
carries(utojr, frjtwx).
carries(utojr, guurpo).
carries(kcpwmyz, oykqvif).
carries(kcpwmyz, ukrjos).
carries(kcpwmyz, mwrnosj).
carries(kcpwmyz, bdjlzf).
carries(qvndh, fyeuhqh).
carries(qvndh, kmbrqv).
carries(qvndh, kgqgct).
carries(qvndh, qtraszq).
carries(lbnenyf, tdhxy).
carries(lbnenyf, ozlqcn).
carries(blpjnzf, gapzarg).
carries(blpjnzf, syxkp).
carries(lfwru, smiucuf).
carries(lfwru, libtrl).
carries(cvnfak, lfykdub).
carries(cvnfak, yxqaa).
carries(ytbyct, yaehsu).
carries(ytbyct, cxcah).
carries(mvjqmad, swaxyxe).
carries(mvjqmad, perbvgz).
carries(uewchd, oqqme).
carries(uewchd, vaeeqvi).
carries(hbtur, mgqkhic).
carries(hbtur, jkvgvz).
carries(anehvd, frezf).
carries(anehvd, wvdoa).
carries(hipfszh, dxavaum).
carries(hipfszh, qkapxbc).
carries(hipfszh, adwir).
carries(yxpnzkn, dxavw).
carries(yxpnzkn, nxpozme).
carries(yxpnzkn, wdjcb).
carries(qzobjfo, vetsll).
carries(qzobjfo, utsfqn).
carries(qzobjfo, dcsxekv).
carries(aqugisv, rddnfg).
carries(aqugisv, qozmho).
carries(aqugisv, pbohgz).
carries(aqugisv, lupyc).
carries(qshoazt, ockzlpp).
carries(qshoazt, yeheld).
carries(qshoazt, judfhye).
carries(wngzh, guauivo).
carries(wngzh, aiwvi).
carries(wngzh, vxruziw).
carries(wngzh, ikqijv).
carries(kxkwxoj, pyvwl).
carries(kxkwxoj, akdffhk).
carries(qdpoyl, aahqtsf).
carries(qdpoyl, lnontej).
carries(qdpoyl, lfiteup).
carries(qdpoyl, oaopxo).
carries(dvncmy, hzfwtzf).
carries(dvncmy, nmtia).
carries(dvncmy, ygiyze).
carries(dvncmy, zuquy).
carries(gsmocx, krmbsc).
carries(gsmocx, ywmif).
carries(laoouso, xvdkt).
carries(laoouso, eogzpga).
carries(yzfzbw, vjevs).
carries(yzfzbw, paqihg).
carries(dkcqdx, wemjk).
carries(dkcqdx, kyuneoo).
carries(dszip, vzbpn).
carries(dszip, xqxgd).
carries(chljtta, dpfvy).
carries(chljtta, nbwkld).
carries(zzcagx, wuvmf).
carries(zzcagx, nrvsqf).
carries(xfglmz, nrlhen).
carries(xfglmz, rfkcylj).
carries(xfglmz, ymkax).
carries(pnsvthy, cadasac).
carries(pnsvthy, rpxmv).
carries(pnsvthy, azkmt).
carries(lonfrp, pohdy).
carries(lonfrp, bnmshvm).
carries(lonfrp, oheank).
carries(lonfrp, qwlze).
carries(lonfrp, dszip).
carries(yngqiv, cayigxg).
carries(yngqiv, ixomyeb).
carries(lfiteup, qnsqwm).
carries(lfiteup, qdpnnex).
carries(lfiteup, cmbnwse).
carries(lfiteup, onaatvy).
carries(zuoczei, ismrc).
carries(zuoczei, dbexmj).
carries(zuoczei, oeqqj).
carries(nwxyrtn, kpgatn).
carries(nwxyrtn, egcjfjo).
carries(bruqu, uwylbft).
carries(bruqu, qntpdh).
carries(qgvqg, iekwfia).
carries(qgvqg, qhrxvzj).
carries(wwhlo, hcyjfzz).
carries(wwhlo, dbuqsj).
carries(wwhlo, latmzh).
carries(wwhlo, geztlsi).
carries(fvwll, axkhzf).
carries(fvwll, mqpbpgq).
carries(qkpaxtt, wohvpbn).
carries(qkpaxtt, fkjwn).
carries(lupyc, rsqihar).
carries(lupyc, moivx).
carries(lupyc, xxoil).
carries(lupyc, vggstn).
carries(ibwve, zfmas).
carries(ibwve, sddvn).
carries(brwsjee, uqpprye).
carries(brwsjee, ejovcx).
carries(ndhitxf, uoxzkp).
carries(ndhitxf, ppossv).
carries(btbnj, jxqzmuv).
carries(btbnj, tycgm).
carries(btbnj, xewbn).
carries(btbnj, rjayavy).
carries(czuwoe, hxzjg).
carries(czuwoe, cfiyqh).
carries(fvkxwt, zuoczei).
carries(fvkxwt, gjwzw).
carries(fvkxwt, qsyocuq).
carries(cwixiq, jvnuwap).
carries(cwixiq, hkweu).
carries(bzbfpkb, zhrsp).
carries(bzbfpkb, rgzrnnl).
carries(ruabtb, xvwio).
carries(ruabtb, lhbwbik).
carries(rkofvt, gkqgru).
carries(rkofvt, xoqvvx).
carries(rkofvt, iqler).
carries(rkofvt, dhaxwd).
carries(utyrttu, wjaocmd).
carries(utyrttu, xwohr).
carries(utyrttu, rxflxr).
carries(kgzyk, iqymm).
carries(kgzyk, asrwh).
carries(ukrqfm, yuiicxp).
carries(ukrqfm, qjnhwpq).
carries(aulgwyb, rhjxbx).
carries(aulgwyb, weguko).
carries(aulgwyb, ppqdnd).
carries(aulgwyb, csmul).
carries(aulgwyb, srscbv).
carries(aulgwyb, kriwb).
carries(weygson, kpnxkyy).
carries(weygson, wdcltyl).
carries(crothf, pwfdn).
carries(crothf, hawmd).
carries(ptawnqq, kcjwb).
carries(ptawnqq, bvknwgq).
carries(ptawnqq, xsddbi).
carries(oicysoz, awgjkiv).
carries(oicysoz, ndszsz).
carries(xhmornc, dnjydir).
carries(xhmornc, icnav).
carries(xhmornc, qyasuw).
carries(wshlljj, ojqqw).
carries(wshlljj, olevfy).
carries(wshlljj, iwiaa).
carries(mjtuzfr, ukaflr).
carries(mjtuzfr, zzsqfm).
carries(zxavxe, swqym).
carries(zxavxe, yreenth).
carries(zxavxe, ubvheu).
carries(eepdcje, cxhuwiw).
carries(eepdcje, damyp).
carries(eepdcje, tmvfp).
carries(efgqua, klhfca).
carries(efgqua, usitmiz).
carries(efgqua, aceqrlu).
carries(uktpcar, ebwgi).
carries(uktpcar, pozpmyh).
carries(dhaxwd, pxhwr).
carries(dhaxwd, qxyramq).
carries(dhaxwd, wphgd).
carries(iciuuh, gslii).
carries(iciuuh, fqaefy).
carries(iciuuh, hwuwj).
carries(khzbxke, ftkflbo).
carries(khzbxke, tracdgp).
carries(zoryb, eusnn).
carries(zoryb, exqkey).
carries(pncxkcd, izpxjp).
carries(pncxkcd, myckhlw).
carries(zlpxr, iuauic).
carries(zlpxr, dznlyl).
carries(pablb, muopf).
carries(pablb, oekhu).
carries(pablb, thzqscd).
carries(qcntm, lvcsn).
carries(qcntm, kpqwup).
carries(qcntm, gosgwz).
carries(qcntm, moiqr).
carries(sycbr, mutwmaa).
carries(sycbr, qmpncds).
carries(sycbr, bfroq).
carries(sycbr, khsdxn).
carries(alzvh, gtpyffj).
carries(alzvh, fzgto).
carries(alzvh, uewchd).
carries(bwaye, rveuz).
carries(bwaye, rcumpgx).
carries(xmbujw, jguufio).
carries(xmbujw, shyxzeh).
carries(xmbujw, pjxauhw).
carries(xmbujw, ytirlv).
carries(urbkrn, seblnmz).
carries(urbkrn, kgfhvte).
carries(wyohotq, vlbsr).
carries(wyohotq, oqdukh).
carries(wyohotq, ssyfvrj).
carries(lurhq, cibzqvo).
carries(lurhq, sycbr).
carries(lurhq, ruabtb).
carries(hydeeqe, jutgp).
carries(hydeeqe, wxudgdd).
carries(hydeeqe, bqtxl).
carries(ecanv, dxloi).
carries(ecanv, whaax).
carries(bmyahis, qpxgye).
carries(bmyahis, ajkztpj).
carries(bmyahis, ywkpvle).
carries(qdyzunw, stbgj).
carries(qdyzunw, loljfo).
carries(cvwsj, stdfrj).
carries(cvwsj, fvjcbib).
carries(cvwsj, ixroc).
carries(cvwsj, ksqrqx).
carries(vfxqcbq, vlgiuef).
carries(vfxqcbq, dojviv).
carries(frikrv, yngqiv).
carries(frikrv, wsoahhs).
carries(frikrv, pncxkcd).
carries(frikrv, gpqhjv).
carries(frikrv, zlpxr).
carries(frikrv, fdumfc).
carries(frikrv, kwavcf).
carries(ikqijv, jcqhl).
carries(ikqijv, nwxyrtn).
carries(ikqijv, vjxldb).
carries(ikqijv, mmtzk).
carries(ikqijv, gnffg).
carries(pyoma, oicysoz).
carries(pyoma, qsbcfm).
carries(pyoma, eepdcje).
carries(pyoma, fhdqcbx).
carries(pyoma, zzcagx).
carries(pyoma, dvipr).
carries(pibqmuz, kgvbcq).
carries(pibqmuz, wuegrv).
carries(qkluh, weunegg).
carries(qkluh, ziiijv).
carries(nqylf, bvenb).
carries(nqylf, njozyy).
carries(nqylf, amxjb).
carries(nqylf, stujlz).
carries(hfymm, uakcbox).
carries(hfymm, kbmse).
carries(hfymm, qvyrm).
carries(nnyago, mxvaxl).
carries(nnyago, uwrfay).
carries(oxzmr, ydowp).
carries(oxzmr, nnnkplx).
carries(oxzmr, grlofut).
carries(kthnd, zbmwego).
carries(kthnd, pvliyn).
carries(kthnd, svsjobu).
carries(kthnd, bzfew).
carries(iqler, vnelda).
carries(iqler, ujpgmwm).
carries(rdomgf, sggimr).
carries(rdomgf, jegoty).
carries(rdomgf, owcwvug).
carries(rdomgf, tcqnso).
carries(vkleczw, uxzwwe).
carries(vkleczw, cupeghk).
carries(naxce, inija).
carries(naxce, cvvegrx).
carries(hxfvc, lqbnqnl).
carries(hxfvc, qguphyk).
carries(vwosnfn, umnkslz).
carries(vwosnfn, rlgbvvj).
carries(kriwb, ziayhmx).
carries(kriwb, zouujb).
carries(kriwb, kcqgcgl).
carries(emhxtcg, uktpcar).
carries(emhxtcg, yjoyyvl).
carries(emhxtcg, blwhz).
carries(emhxtcg, bvbtxh).
carries(emhxtcg, jkoyyzg).
carries(emhxtcg, cdnwq).
carries(fzgto, qcntm).
carries(fzgto, tzvld).
carries(fzgto, yohxzv).
carries(fzgto, ttmnf).
carries(fzgto, hbtur).
carries(ymxwlpc, ngjngv).
carries(ymxwlpc, jcdmhvd).
carries(ymxwlpc, nqylf).
carries(ymxwlpc, ecytwe).
carries(ymxwlpc, iciuuh).
carries(emkzxk, krfqcf).
carries(emkzxk, sybpjci).
carries(sejkvk, kojry).
carries(sejkvk, tdwxgv).
carries(dpyxxkv, dtkdwp).
carries(dpyxxkv, rehst).
carries(vsfgg, mtrde).
carries(vsfgg, xpzpv).
carries(vsfgg, etwpt).
carries(vsfgg, dvncmy).
carries(ttmnf, qrzjlw).
carries(ttmnf, gwudp).
carries(zsigmj, eazvkxv).
carries(zsigmj, ticdma).
carries(oaopxo, jeopf).
carries(oaopxo, wphtnvm).
carries(qozmho, btrepl).
carries(qozmho, gljkci).
carries(qozmho, parvx).
carries(qozmho, onwgja).
carries(lvdff, wqokqz).
carries(lvdff, zyaab).
carries(ixreefh, auqyep).
carries(ixreefh, jgnklq).
carries(pwhmf, iujytuv).
carries(pwhmf, iieico).
carries(sawpop, piyqfs).
carries(sawpop, wfamtnm).
carries(ccjtpv, oipqc).
carries(ccjtpv, vxlypal).
carries(odxyfb, biglt).
carries(odxyfb, irjov).
carries(odxyfb, pibqmuz).
carries(qgcvk, oizmgt).
carries(qgcvk, apqby).
carries(qgcvk, ecanv).
carries(blwhz, cihzh).
carries(blwhz, sttus).
carries(ruvfo, dlhyzjw).
carries(ruvfo, skdylgb).
carries(nzvpgv, kwmao).
carries(nzvpgv, ofgeu).
carries(fhhrji, faudqy).
carries(fhhrji, bxcdldt).
carries(qdpnnex, nwyulno).
carries(qdpnnex, uxbjym).
carries(gatjls, gkxebo).
carries(gatjls, xmogef).
carries(qidmgsc, hpgwq).
carries(qidmgsc, szvty).
carries(oboju, cprbzvp).
carries(oboju, xbytmo).
carries(ajxsrs, vwslb).
carries(ajxsrs, wmukud).
carries(inknun, mfutay).
carries(inknun, nzdbs).
carries(nkdxy, ccqldu).
carries(nkdxy, fkrog).
carries(sfohocq, fkjof).
carries(sfohocq, gcrbrn).
carries(olofh, uqtiwgu).
carries(olofh, xsmcfs).
carries(thneux, choeijs).
carries(thneux, lodcj).
carries(sftqzaf, qybit).
carries(sftqzaf, dpoat).
carries(sawkpue, modms).
carries(sawkpue, ssrqm).
carries(sawkpue, ndgzf).
carries(sawkpue, sqvxf).
carries(xklrgp, yfrmup).
carries(xklrgp, nfhaii).
carries(xklrgp, uspmxw).
carries(jbarvch, qtqcv).
carries(jbarvch, prvldv).
carries(sktewq, fxfznc).
carries(sktewq, venvbai).
carries(sktewq, rxgry).
carries(zffpxgw, hpcmne).
carries(zffpxgw, ajiubh).
carries(egzpjym, hasyyr).
carries(egzpjym, vgjgz).
carries(jopcvyb, tgwgno).
carries(jopcvyb, uyhlbf).
carries(jopcvyb, rdomgf).
carries(jopcvyb, yrozpm).
carries(jopcvyb, qnscqms).
carries(jopcvyb, ubhlb).
carries(jkoyyzg, urqox).
carries(jkoyyzg, yfnlhlh).
carries(jtqijee, auciw).
carries(jtqijee, awqgdfk).
carries(jtqijee, uceyfx).
carries(jtqijee, awjwff).
carries(gxpuofv, cxptwu).
carries(gxpuofv, zrwnma).
carries(gxpuofv, mxgyt).
carries(rfkcylj, ckypedd).
carries(rfkcylj, xjufehm).
carries(rfkcylj, nbkzvz).
carries(rkwkwd, dfzwcc).
carries(rkwkwd, pmgngjy).
carries(rkwkwd, ejnqcb).
carries(fkjlcz, mjrog).
carries(fkjlcz, qmnji).
carries(vgkltqq, wzxyc).
carries(vgkltqq, uodhr).
carries(vgkltqq, xsjbc).
carries(dfwpczh, bkjppqe).
carries(dfwpczh, yuhmnjs).
carries(zejjjo, aoipta).
carries(zejjjo, bbbms).
carries(bwiqe, dtburx).
carries(bwiqe, bpgdb).
carries(bwiqe, fhhrji).
carries(bwiqe, hfymm).
carries(bwiqe, tgqwgb).
carries(bwiqe, gxpuofv).
carries(ktcdxoo, efobdsd).
carries(ktcdxoo, jtmps).
carries(ktcdxoo, zmjqiv).
carries(tvinpl, iglmzsi).
carries(tvinpl, zujrs).
carries(qwlze, nvtyg).
carries(qwlze, hzywspw).
carries(bzbvwgh, kbwpk).
carries(bzbvwgh, czuwoe).
carries(bzbvwgh, tpekc).
carries(bzbvwgh, qidmgsc).
carries(bzbvwgh, hagrq).
carries(cstmu, mkrjamh).
carries(cstmu, vycgaoz).
carries(cstmu, ruvfo).
carries(cstmu, sawpop).
carries(umutl, grtrt).
carries(umutl, tjaqrw).
carries(olrdlw, fxqng).
carries(olrdlw, irvolb).
carries(jdhewio, qpden).
carries(jdhewio, olspso).
carries(szszezd, tvcxl).
carries(szszezd, mdnqs).
carries(szszezd, waxkga).
carries(szszezd, gyjvtjm).
carries(szszezd, ytbyct).
carries(egdrn, fdzqz).
carries(egdrn, urkya).
carries(egdrn, nhteaei).
carries(egdrn, xjypx).
carries(eoaoxqm, khzbxke).
carries(eoaoxqm, pwhmf).
carries(eoaoxqm, kapxuq).
carries(qkmkwgl, tyywgp).
carries(qkmkwgl, xjhvuc).
carries(fmwvok, cksiby).
carries(fmwvok, uravet).
carries(fmwvok, wexhnbh).
carries(fmwvok, nnyago).
carries(fmwvok, thneux).
carries(xybiuiq, egrimlf).
carries(xybiuiq, cdvhmy).
carries(xybiuiq, hqwkq).
carries(xybiuiq, wfwbq).
carries(xlanm, bwmrksn).
carries(xlanm, fimqsn).
carries(xlanm, naxce).
carries(xlanm, zjtjt).
carries(tumwln, qgvqg).
carries(tumwln, sawkpue).
carries(tumwln, tcvgl).
carries(tumwln, zqnjd).
carries(onamlmy, kzxyyd).
carries(onamlmy, yiqnfd).
carries(jtmps, wixoky).
carries(jtmps, vmsmdqx).
carries(jtmps, lxbsif).
carries(xrkqv, xgihtsx).
carries(xrkqv, iunkpe).
carries(mcjlm, qkluh).
carries(mcjlm, bsfgu).
carries(mcjlm, ndhitxf).
carries(mcjlm, jtqijee).
carries(mcjlm, ifgfg).
carries(mcjlm, wvhvw).
carries(bmfhjo, bznst).
carries(bmfhjo, xcgwl).
carries(kwxpnrs, rmnkgss).
carries(kwxpnrs, cciwr).
carries(mpnnffx, wayftw).
carries(mpnnffx, epaaasn).
carries(xsfefyb, xybiuiq).
carries(xsfefyb, jnzqvia).
carries(xsfefyb, eywfmfs).
carries(ejzsbli, djsss).
carries(ejzsbli, rkhyewd).
carries(cxetjr, fujwb).
carries(cxetjr, nnxqmb).
carries(cxetjr, kthnd).
carries(ywhjz, exesam).
carries(ywhjz, odbyxq).
carries(ywhjz, xghhu).
carries(ywhjz, xmbujw).
carries(rxezd, sohuv).
carries(rxezd, ksfss).
carries(hfhswyd, tqyldbt).
carries(hfhswyd, tridq).
carries(zkvopb, nxqzuy).
carries(zkvopb, jpwwg).
carries(sfruur, twbxgv).
carries(sfruur, evows).
carries(sfruur, xwwzp).
carries(sfruur, vsfgg).
carries(sfruur, zsasjr).
carries(fwocscd, krolgpf).
carries(fwocscd, gbmfzzu).
carries(wfjks, ekleund).
carries(wfjks, kikntw).
carries(wfjks, jubtls).
carries(wfjks, npjcdl).
carries(bvbtxh, zyzet).
carries(bvbtxh, pflvdx).
carries(bvbtxh, ontrln).
carries(obzomb, ullvx).
carries(obzomb, acfmyv).
carries(obzomb, mzywzs).
carries(khupkt, alzvh).
carries(khupkt, sjhwgq).
carries(khupkt, lyxzfqz).
carries(vxruziw, tpvzavf).
carries(vxruziw, xrkqv).
carries(vxruziw, qvndh).
carries(vxruziw, xklrgp).
carries(vxruziw, cwixiq).
carries(svcafxb, jbarvch).
carries(svcafxb, mawwtx).
carries(svcafxb, stkcndh).
carries(dhejgd, tzhoqw).
carries(dhejgd, cvrqij).
carries(dhejgd, xokmont).
carries(waxkga, rgxwwc).
carries(waxkga, yriibfp).
carries(tlmxygb, rvyqbq).
carries(tlmxygb, olofh).
carries(tlmxygb, egdrn).
carries(tlmxygb, pkudedc).
carries(tlmxygb, rxezd).
carries(tlmxygb, csnhv).
carries(tlmxygb, jrgougl).
carries(nzhnurq, zwxwfin).
carries(nzhnurq, lwvcp).
carries(vtvsd, cnsbonb).
carries(vtvsd, ajhizdz).
carries(ockzlpp, chxsxbr).
carries(ockzlpp, vbvug).
carries(fdumfc, lninq).
carries(fdumfc, ykowao).
carries(gtpew, iyxsjhc).
carries(gtpew, fwvvidu).
carries(gtpew, mdshsxt).
carries(gtpew, yzvqo).
carries(stkcndh, cohps).
carries(stkcndh, legrbb).
carries(nbrfpbr, iedrlkp).
carries(nbrfpbr, rtyegs).
carries(nbrfpbr, hxfvc).
carries(qeiijk, jiaho).
carries(qeiijk, qlxgnl).
carries(zmjqiv, jwjrj).
carries(zmjqiv, bwfqr).
carries(jdxfsa, lugwl).
carries(jdxfsa, ckcjr).
carries(jdxfsa, umutl).
carries(jlgnsu, wxvuup).
carries(jlgnsu, ilvblzm).
carries(jlgnsu, ckzuyha).
carries(jlgnsu, cbbtbz).
carries(pjsbxvk, dfwpczh).
carries(pjsbxvk, gsmocx).
carries(pjsbxvk, fwocscd).
carries(iiwwr, hmnvh).
carries(iiwwr, vksnzty).
carries(sysvory, udpcyt).
carries(sysvory, yrdhq).
carries(sysvory, ealyedu).
carries(sysvory, kmufvuk).
carries(zjtjt, xqshwdz).
carries(zjtjt, khjag).
carries(aiwvi, walkm).
carries(aiwvi, ixreefh).
carries(aiwvi, gatjls).
carries(aiwvi, spgwj).
carries(aiwvi, kjdjdr).
carries(aiwvi, ybnehoi).
carries(rvyqbq, bxqjg).
carries(rvyqbq, sxzpils).
carries(tgqwgb, zxrmy).
carries(tgqwgb, qvmbysw).
carries(dbnoug, xnvdqbe).
carries(dbnoug, mtowovz).
carries(dbnoug, bzbncmc).
carries(exesam, fhjzpjw).
carries(exesam, qxjknv).
carries(djimr, ltgnnr).
carries(djimr, kjmse).
carries(aflcmu, ezycquw).
carries(aflcmu, kaecmob).
carries(utamsb, llrrzrn).
carries(utamsb, erbssqe).
carries(umhjck, zepjndx).
carries(umhjck, bdmah).
carries(ngjngv, jqnnot).
carries(ngjngv, bnjwfrz).
carries(cibzqvo, dfrcge).
carries(cibzqvo, uuixxr).
carries(rgelh, tmigcw).
carries(rgelh, jmzvi).
carries(rgelh, tjslk).
carries(rgelh, blpjnzf).
carries(rgelh, qzobjfo).
carries(rgelh, rcmyfr).
carries(rgelh, bwaye).
carries(biglt, rihlj).
carries(biglt, odoxr).
carries(bsfgu, iinxvw).
carries(bsfgu, sgpiiir).
carries(plkmpm, bieok).
carries(plkmpm, grrxl).
carries(ywzai, khuess).
carries(ywzai, vbauj).
carries(weguko, iuwwa).
carries(weguko, epydl).
carries(tbdhh, sfwaimh).
carries(tbdhh, orihc).
carries(tbdhh, jsuak).
carries(mhpxyvm, xdkya).
carries(mhpxyvm, zsigmj).
carries(mhpxyvm, umhjck).
carries(judfhye, brlzr).
carries(judfhye, dxffr).
carries(qsbcfm, fqayb).
carries(qsbcfm, xminmbj).
carries(zgoinf, xljycl).
carries(zgoinf, ghfcfj).
carries(vbvxs, akzcjd).
carries(vbvxs, vnynj).
carries(vbvxs, eanoucd).
carries(vbvxs, txxfz).
carries(csmul, wfdkce).
carries(csmul, oaqvt).
carries(fzzlnwi, vgkltqq).
carries(fzzlnwi, vbvxs).
carries(fzzlnwi, lfwru).
carries(ywegjjk, rgelh).
carries(ywegjjk, sfizdf).
carries(ywegjjk, mcjlm).
carries(ywegjjk, ztjquwi).
carries(gyjvtjm, paynlu).
carries(gyjvtjm, nfklqi).
carries(ecfrqpl, okniwp).
carries(ecfrqpl, njqemt).
carries(nsxrvpg, nqtowev).
carries(nsxrvpg, fblafmm).
carries(iwiaa, ztfhz).
carries(iwiaa, txtdw).
carries(iwiaa, jpnhog).
carries(tbaai, vrqbi).
carries(tbaai, jjdmu).
carries(hdmcpq, qitnlrh).
carries(hdmcpq, wsmmlrl).
carries(aukjf, okxucaz).
carries(aukjf, otbxl).
carries(vilskw, vahnoue).
carries(vilskw, wqzic).
carries(upsmxqn, bmyahis).
carries(upsmxqn, xanbjlw).
carries(upsmxqn, twazofk).
carries(kapxuq, wzybp).
carries(kapxuq, tdstv).
carries(ydqgvnf, flejt).
carries(ydqgvnf, dxpxept).
carries(mxtxm, tdknh).
carries(mxtxm, pjbwq).
carries(ziprwty, pshwly).
carries(ziprwty, jwojmds).
carries(ziprwty, tgsicj).
carries(rhjxbx, mhdkdt).
carries(rhjxbx, kwzgwt).
carries(yenln, wklmops).
carries(yenln, ulehitr).
carries(yenln, dbnoug).
carries(yenln, wyohotq).
carries(yenln, gjqwe).
carries(ntcddy, qekpce).
carries(ntcddy, gjgwki).
carries(ntcddy, dkkkntv).
carries(irjov, bzdgxs).
carries(irjov, zkbeehu).
carries(oztasey, dxddn).
carries(oztasey, foibc).
carries(ogyiesm, eoaoxqm).
carries(ogyiesm, lptmne).
carries(ogyiesm, titze).
carries(ojqqw, yxsaf).
carries(ojqqw, zfshwt).
carries(liwlcz, fhvyhk).
carries(liwlcz, qqnywdg).
carries(liwlcz, ajxsrs).
carries(liwlcz, utojr).
carries(liwlcz, tvinpl).
carries(jfchk, hbwec).
carries(jfchk, weithhz).
carries(piqids, fbusld).
carries(piqids, xifaq).
carries(piqids, vkwsodp).
carries(klnxfd, zoryb).
carries(klnxfd, wcpyi).
carries(klnxfd, etjste).
carries(xanbjlw, uuapl).
carries(xanbjlw, sckgsn).
carries(xdkya, bvcghhs).
carries(xdkya, jzpdbe).
carries(lcgtwj, pxsokyl).
carries(lcgtwj, chhhge).
carries(cvprip, qkpaxtt).
carries(cvprip, bmfhjo).
carries(cvprip, tqimh).
carries(qnsqwm, brnhg).
carries(qnsqwm, trcyfi).
carries(yjrar, jppsaym).
carries(yjrar, agfnncm).
carries(hechfb, aflcmu).
carries(hechfb, sjdpe).
carries(hechfb, ofdehn).
carries(hechfb, zgoinf).
carries(hechfb, umnqkb).
carries(jrgougl, jrkbay).
carries(jrgougl, elpwvoy).
carries(jrgougl, gnqwwbt).
carries(jrgougl, ipxns).
carries(wsoahhs, zouxmz).
carries(wsoahhs, brghw).
carries(qopkhc, cvrga).
carries(qopkhc, ujtej).
carries(qopkhc, gybikf).
carries(qopkhc, dkoike).
carries(qopkhc, guhjkd).
carries(lvcdsgp, afelswv).
carries(lvcdsgp, ovhhkoc).
carries(lvcdsgp, rugnh).
carries(jkodco, adunt).
carries(jkodco, ztook).
carries(velhob, gyzorus).
carries(velhob, kfngejn).
carries(cfrcco, zhhhntj).
carries(cfrcco, jcvimc).
carries(tnhet, onoyb).
carries(tnhet, laohhtn).
carries(tnhet, mqlgoq).
carries(evows, xsfwcgq).
carries(evows, txszqu).
carries(evows, uypxc).
carries(evows, aulgwyb).
carries(evows, qshoazt).
carries(evows, dyfnpt).
carries(evows, rkofvt).
carries(dtburx, frycrnj).
carries(dtburx, vqrtnp).
carries(mgyixhn, msskm).
carries(mgyixhn, iqtemv).
carries(bckbud, iqjbdok).
carries(bckbud, mjtuzfr).
carries(bckbud, zejjjo).
carries(lwqlyjq, qongfb).
carries(lwqlyjq, pzlhzky).
carries(yqlxeb, ymxwlpc).
carries(yqlxeb, cavlg).
carries(yqlxeb, odxyfb).
carries(yqlxeb, xsfefyb).
carries(yqlxeb, mhpxyvm).
carries(yqlxeb, htujh).
carries(yqlxeb, xfglmz).
carries(oplzouv, fqfnocq).
carries(oplzouv, ntftmt).
carries(oplzouv, piqids).
carries(oplzouv, dbpkf).
carries(oplzouv, gtpew).
carries(puvhc, bsfsayz).
carries(puvhc, ssxuat).
carries(puvhc, brlbdjx).
carries(gnffg, vjzfc).
carries(gnffg, ijyhvsj).
carries(tfqxv, zmtfcll).
carries(tfqxv, gcdzhfy).
carries(lnontej, bpelccj).
carries(lnontej, utyrttu).
carries(lnontej, gqlyhql).
carries(lnontej, fvwll).
carries(lnontej, ejzsbli).
carries(lnontej, nsxrvpg).
carries(lnontej, ofyuao).
carries(gjwzw, egzpjym).
carries(gjwzw, ywzai).
carries(gjwzw, bfulyh).
carries(gjwzw, zxavxe).
carries(bwugxhi, vbzwk).
carries(bwugxhi, krrvyl).
carries(bwugxhi, ivlac).
carries(bwugxhi, mzrwaa).
carries(uypxc, bpzjm).
carries(uypxc, dkcqdx).
carries(uypxc, msryw).
carries(uypxc, aqlqmq).
carries(uypxc, yxpnzkn).
carries(uypxc, obzomb).
carries(uypxc, bzbfpkb).
carries(nfkmi, drzge).
carries(nfkmi, bgpjb).
carries(nfkmi, jkodco).
carries(nfkmi, kxkwxoj).
carries(nfkmi, crothf).
carries(fqfnocq, yacmhtk).
carries(fqfnocq, vonesxw).
carries(cejnfcx, rhlepi).
carries(cejnfcx, rgkrl).
carries(cejnfcx, gjgcvyp).
carries(cejnfcx, lkfdr).
carries(guhjkd, cdcvlb).
carries(guhjkd, cider).
carries(guhjkd, qpjzx).
carries(ayhdd, laeaf).
carries(ayhdd, udiio).
carries(ayhdd, bgqvm).
carries(ayhdd, ofwtjhw).
carries(onaatvy, aftzw).
carries(onaatvy, ekxczvo).
carries(onaatvy, wkfjzs).
carries(cnblx, vkleczw).
carries(cnblx, pablb).
carries(cnblx, objssr).
carries(cnblx, pzjvq).
carries(tynxlau, ywegjjk).
carries(tynxlau, bavyg).
carries(tynxlau, qdpoyl).
carries(tynxlau, wngzh).
carries(soryrk, fnzskbi).
carries(soryrk, oovqoi).
carries(nrlhen, wattsr).
carries(nrlhen, eqbwx).
carries(zsasjr, jopcvyb).
carries(zsasjr, pyoma).
carries(zsasjr, jdxfsa).
carries(zsasjr, liwlcz).
carries(zsasjr, cxetjr).
carries(zsasjr, vifbi).
carries(zsasjr, tlmxygb).
carries(titze, czmzol).
carries(titze, velhob).
carries(titze, truximz).
carries(titze, utamsb).
carries(bjcsjrr, bpemyk).
carries(bjcsjrr, nqjuj).
carries(ismrc, cjeauo).
carries(ismrc, uasqon).
carries(ismrc, prxmxv).
carries(cksiby, zzbzwdm).
carries(cksiby, zdawjkr).
carries(rgkapf, dkjlges).
carries(rgkapf, ckombz).
carries(rgkapf, vpnjbha).
carries(ujtej, ccuehkp).
carries(ujtej, tflwng).
carries(mawwtx, bvrpb).
carries(mawwtx, xpvukx).
carries(mawwtx, jhbqc).
carries(jinwsas, gzctkm).
carries(jinwsas, nxmksiq).
carries(jinwsas, fhyvz).
carries(sjdpe, erfldtn).
carries(sjdpe, vuzxr).
carries(tiwkyz, lewbxa).
carries(tiwkyz, btnnorn).
carries(kbwpk, ffhxi).
carries(kbwpk, polumk).
carries(gkqgru, pqlwekx).
carries(gkqgru, ysdqkw).
carries(baaqr, btnyx).
carries(baaqr, fdszkhp).
carries(jmzvi, rzwjli).
carries(jmzvi, uizop).
carries(jmzvi, necqpdx).
carries(jmzvi, debir).
carries(wklmops, mbkbmql).
carries(wklmops, dlkhb).
carries(ofdehn, yiteow).
carries(ofdehn, yblsbf).
carries(ofdehn, gazaoty).
carries(ofdehn, lzeihwp).
carries(qrlhp, moqped).
carries(qrlhp, ueasp).
carries(bwmrksn, bxkxp).
carries(bwmrksn, eajmafa).
carries(qdcos, ryctwjl).
carries(qdcos, sczyp).
carries(qdcos, enxbya).
carries(qdcos, cpmpyvq).
carries(ttqpi, nfmicyi).
carries(ttqpi, yjnrjde).
carries(cdnwq, xerbuu).
carries(cdnwq, iiiof).
carries(cdnwq, jaerxmv).
carries(cdnwq, bdwbjzh).
carries(krpda, azzysl).
carries(krpda, ayhdd).
carries(krpda, tnhet).
carries(seihhya, jhruwih).
carries(seihhya, aefqoq).
carries(jcqhl, glxogmc).
carries(jcqhl, bsqilyq).
carries(walkm, cxuijad).
carries(walkm, yanvh).
carries(jcezw, wxbao).
carries(jcezw, predg).
carries(iqjbdok, msrrlv).
carries(iqjbdok, kodrhj).
carries(srscbv, jawbtmo).
carries(srscbv, wmvniap).
carries(jtmuv, terkw).
carries(jtmuv, bzbvwgh).
carries(jtmuv, emhxtcg).
carries(jtmuv, nkbmoin).
carries(edtkfvv, tbdhh).
carries(edtkfvv, mpnnffx).
carries(edtkfvv, wdzhfmw).
carries(edtkfvv, pkceuqw).
carries(tqimh, prlhyb).
carries(tqimh, kqueox).
carries(lyxzfqz, qgcvk).
carries(lyxzfqz, jfchk).
carries(lyxzfqz, upsmxqn).
carries(lyxzfqz, nbrfpbr).
carries(lyxzfqz, jmbueky).
carries(lyxzfqz, kqswas).
carries(poypmax, atyaqz).
carries(poypmax, vkhazkn).
carries(poypmax, chljtta).
carries(poypmax, anehvd).
carries(poypmax, vilskw).
carries(poypmax, lbnenyf).
carries(pkudedc, takxgz).
carries(pkudedc, fupwuk).
carries(oizmgt, sakhif).
carries(oizmgt, fwohcn).
carries(pzjvq, ieebfpb).
carries(pzjvq, yprusb).
carries(oeqqj, pwhplm).
carries(oeqqj, jlwzgg).
carries(jmbueky, iiwwr).
carries(jmbueky, cvwsj).
carries(jmbueky, yvwecfs).
carries(eywfmfs, mfamq).
carries(eywfmfs, bqoptf).
carries(ghsxqq, srsenpj).
carries(ghsxqq, uskfp).
carries(qnevjto, dcqinx).
carries(qnevjto, uctlk).
carries(tkvmtol, vfkjif).
carries(tkvmtol, oinyx).
carries(xycva, aclihvm).
carries(xycva, yaripcu).
carries(mtrde, gsfnr).
carries(mtrde, plsep).
carries(hykxm, dpyxxkv).
carries(hykxm, plkmpm).
carries(hykxm, pknqf).
carries(twbxgv, yenln).
carries(twbxgv, qrgqcd).
carries(twbxgv, tfqxv).
carries(cjhtxo, gfasdd).
carries(cjhtxo, psmztc).
carries(cjhtxo, rdvtzr).
carries(dhuof, ysakcag).
carries(dhuof, dehjjod).
carries(wkcrce, ndvdj).
carries(wkcrce, ieohkpr).
carries(evbvdgl, titbn).
carries(evbvdgl, ebnqn).
carries(rydrp, mbniyi).
carries(rydrp, emrbwzz).
carries(tpvzavf, fdaqst).
carries(tpvzavf, qlkjhsi).
carries(krbpgmk, svcafxb).
carries(krbpgmk, vfxzkq).
carries(krbpgmk, vxwobup).
carries(krbpgmk, qopkhc).
carries(bpzjm, loxjzpo).
carries(bpzjm, fzvdchs).
carries(ntftmt, welvrkn).
carries(ntftmt, htouwcr).
carries(etwpt, cejnfcx).
carries(etwpt, oxzmr).
carries(etwpt, sysvory).
carries(csnhv, smsoi).
carries(csnhv, lkwogh).
carries(lisfhnn, zykcrir).
carries(lisfhnn, sxvig).
carries(lisfhnn, wvtac).
carries(drzge, vbmqrqx).
carries(drzge, wgcgdvt).
carries(gsmcgor, rffwau).
carries(gsmcgor, qqmlvk).
carries(rsjffj, klnxfd).
carries(rsjffj, oplzouv).
carries(rsjffj, djimr).
carries(rsjffj, ktcdxoo).
carries(rsjffj, aqugisv).
carries(dyfnpt, xwwfi).
carries(dyfnpt, urbkrn).
carries(dyfnpt, kryczad).
carries(truximz, imxro).
carries(truximz, izyxppl).
carries(qrgqcd, rgkapf).
carries(qrgqcd, tzszs).
carries(qrgqcd, qbzeji).
carries(qrgqcd, nkdxy).
carries(qsyocuq, qilhudr).
carries(qsyocuq, aukjf).
carries(qsyocuq, offkzc).
carries(terkw, yjrar).
carries(terkw, hipfszh).
carries(terkw, oboju).
carries(terkw, tiwkyz).
carries(terkw, vtwdqkd).
carries(terkw, dhuof).
carries(aqlqmq, zhlfdac).
carries(aqlqmq, kkmidak).
carries(tpekc, irhslmm).
carries(tpekc, yunpioi).
carries(ibdjxl, kmrmxw).
carries(ibdjxl, htbmh).
carries(ibdjxl, aslvy).
carries(yohxzv, kvpsfgk).
carries(yohxzv, mctsts).
carries(stnnf, jytapdu).
carries(stnnf, kkeuh).
carries(stnnf, xycva).
carries(stnnf, zffpxgw).
carries(stnnf, cvlkltp).
carries(stnnf, lvdff).
carries(iedrlkp, xiwnu).
carries(iedrlkp, gezqw).
carries(vgqmfj, idwpug).
carries(vgqmfj, hawtu).
carries(dbpkf, zzcqptv).
carries(dbpkf, vfykuuv).

bottomCarrier(X) :- writeln(X), carries(Y, X), bottomCarrier(Y).

result :- bottomCarrier(vfykuuv).
